# Generated by Django 4.2.11 on 2024-04-04 12:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('TenChuyenXe', models.CharField(max_length=255)),
                ('Giodi', models.CharField(max_length=255)),
                ('Gioden', models.CharField(max_length=255)),
                ('Cho_trong', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_KH', models.CharField(max_length=255)),
                ('NgaySinh', models.CharField(max_length=255)),
                ('GioiTinh', models.CharField(max_length=25)),
                ('DiaChi', models.CharField(max_length=255)),
                ('CMND', models.CharField(max_length=255)),
                ('DienThoai', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Loai_ghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_loai', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Loai_NV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_loai', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LoaiKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_Loai', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_loai', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_NV', models.CharField(max_length=255)),
                ('NgaySinh', models.CharField(max_length=255)),
                ('GioiTinh', models.CharField(max_length=25)),
                ('DiaChi', models.CharField(max_length=255)),
                ('CMND', models.CharField(max_length=255)),
                ('DienThoai', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Ma_loai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.loai_nv')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaiXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_taixe', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(max_length=255)),
                ('GioiTinh', models.CharField(max_length=25)),
                ('NgaySinh', models.CharField(max_length=255)),
                ('CMND', models.CharField(max_length=255)),
                ('DienThoai', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TuyenXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_tuyen', models.CharField(max_length=255)),
                ('Diendi', models.CharField(max_length=255)),
                ('Diemden', models.CharField(max_length=255)),
                ('BangGia', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_xe', models.CharField(max_length=255)),
                ('Bien_so', models.CharField(max_length=255)),
                ('So_ghe', models.CharField(max_length=255)),
                ('Ma_loai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.loaixe')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ve_Xe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ten_ve', models.CharField(max_length=255)),
                ('Ma_Chuyen_Xe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.chuyenxe')),
                ('Ma_KH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.khachhang')),
                ('Ma_NV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.nhanvien')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='khachhang',
            name='Ma_loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.loaikhachhang'),
        ),
        migrations.CreateModel(
            name='Ghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('So_ghe', models.CharField(max_length=255)),
                ('Loai_ghe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.loaixe')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='Ma_Tuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.tuyenxe'),
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='Ma_taixe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.taixe'),
        ),
        migrations.CreateModel(
            name='Chi_Tiet_Ve_Xe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Ghichu', models.CharField(max_length=255)),
                ('Ma_Ve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.ve_xe')),
                ('Ma_Xe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.xe')),
                ('Vi_tri_ghe_ngoi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.ghe')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
