# Generated by Django 4.2.11 on 2024-04-11 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0002_rename_ma_taixe_chuyenxe_ma_taixe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_ve_xe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chi_tiet_ve_xe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ghe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ghe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_ghe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_ghe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_nv',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_nv',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaikhachhang',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaikhachhang',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ve_xe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ve_xe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='xe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='xe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 35, 48, 167279, tzinfo=datetime.timezone.utc)),
        ),
    ]
