# Generated by Django 4.2.11 on 2024-04-11 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0003_alter_chi_tiet_ve_xe_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(default=1, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='chi_tiet_ve_xe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chi_tiet_ve_xe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ghe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ghe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_ghe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_ghe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_nv',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loai_nv',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaikhachhang',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaikhachhang',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ve_xe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ve_xe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='xe',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='xe',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 11, 49, 16, 495761, tzinfo=datetime.timezone.utc)),
        ),
    ]
