# Generated by Django 4.2.11 on 2024-04-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0006_alter_chi_tiet_ve_xe_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhanvien',
            old_name='image',
            new_name='avatar',
        ),
    ]
