# Generated by Django 4.2.11 on 2024-04-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0008_alter_khachhang_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachhang',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='taixe',
            old_name='image',
            new_name='avatar',
        ),
    ]
