# Generated by Django 4.2.11 on 2024-05-22 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0012_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyenxe',
            name='Ngay',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
