# Generated by Django 4.2.11 on 2024-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0013_chuyenxe_ngay'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyenxe',
            name='Noiden',
            field=models.CharField(default='Bến Xe', max_length=255),
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='Noidi',
            field=models.CharField(default='Bến Xe', max_length=255),
        ),
    ]
