# Generated by Django 4.2.11 on 2024-05-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0014_chuyenxe_noiden_chuyenxe_noidi'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyenxe',
            name='Ma_Xe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BanVe.xe'),
        ),
    ]
