# Generated by Django 4.2.11 on 2024-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0016_remove_chi_tiet_ve_xe_ma_ve_chi_tiet_ve_xe_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghe',
            name='trangthai',
            field=models.CharField(default='Còn trống', max_length=255),
        ),
    ]
