# Generated by Django 4.2.11 on 2024-05-24 18:37

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0017_ghe_trangthai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khach_di',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('Ten_KH', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(max_length=255)),
                ('CMND', models.CharField(max_length=255)),
                ('DienThoai', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
