# Generated by Django 4.2.11 on 2024-05-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0018_khach_di'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chi_tiet_ve_xe',
            name='Vi_tri_ghe_ngoi',
        ),
        migrations.AddField(
            model_name='chi_tiet_ve_xe',
            name='ghengoi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
