# Generated by Django 4.2.11 on 2024-05-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0019_remove_chi_tiet_ve_xe_vi_tri_ghe_ngoi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chi_tiet_ve_xe',
            name='ghengoi',
        ),
        migrations.RemoveField(
            model_name='ve_xe',
            name='Ten_ve',
        ),
        migrations.AddField(
            model_name='chi_tiet_ve_xe',
            name='Vi_tri_ghe_ngoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BanVe.ghe'),
        ),
    ]
