# Generated by Django 4.2.11 on 2024-05-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0021_alter_ve_xe_ma_nhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ve_xe',
            name='Ma_KhachHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BanVe.khach_di'),
        ),
    ]
