# Generated by Django 4.2.11 on 2024-05-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0022_alter_ve_xe_ma_khachhang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chi_tiet_ve_xe',
            old_name='vexe',
            new_name='Ma_Ve',
        ),
        migrations.RemoveField(
            model_name='chi_tiet_ve_xe',
            name='user',
        ),
    ]
