# Generated by Django 4.2.11 on 2024-05-27 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0023_rename_vexe_chi_tiet_ve_xe_ma_ve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chi_tiet_ve_xe',
            old_name='Ma_Ve',
            new_name='vexe',
        ),
        migrations.AddField(
            model_name='chi_tiet_ve_xe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chi_tiet_ve_xe',
            name='Ma_Xe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BanVe.xe'),
        ),
        migrations.AlterField(
            model_name='chi_tiet_ve_xe',
            name='Vi_tri_ghe_ngoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BanVe.ghe'),
        ),
    ]
