# Generated by Django 4.2.11 on 2024-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0024_rename_ma_ve_chi_tiet_ve_xe_vexe_chi_tiet_ve_xe_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve_xe',
            name='Gia',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
