# Generated by Django 4.2.11 on 2024-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0025_ve_xe_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve_xe',
            name='trangthai_TT',
            field=models.CharField(default='trực tiếp', max_length=255),
        ),
    ]
