# Generated by Django 4.2.11 on 2024-05-31 16:35

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0026_ve_xe_trangthai_tt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgayLe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('Le', models.CharField(max_length=255)),
                ('Tang', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
