# Generated by Django 4.2.11 on 2024-06-02 12:14

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0027_ngayle'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loainguoidung',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='loainguoidung',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loainguoidung',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loainguoidung',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
